### PR TITLE
Avoid warnings in tests

### PR DESCRIPTION
**Pull request by odelalleau**

### CODE REVIEW

**Comment by omry** [comment]
Did we lose coverage?

**Comment by Jasha10** [comment]
> Did we lose coverage?

By default, pytest does not fail if there are warnings. It just prints the warnings to stdout after the tests are finished.

**Comment by omry** [comment]
You can change the noxfile in omegaconf to fail on warnings like it does on Hydra.

**Review by Jasha10 — APPROVED** [review]

**Comment by odelalleau** [comment]
I'm merging so that #711 can go in

**Pull request merged**
