### PR TITLE
improve error message when creating a DictConfig from a bad dataclass

### LINKED ISSUE #658: Opaque ValidationError when calling OmegaConf.create() on dataclass
**Describe the bug**
Calling `OmegaConf.create()` on a dataclass with defaults results in a `ValidationError` that does not specify the field that caused the error.
```bash
omegaconf.errors.ValidationError: Invalid value assigned : int is not a ListConfig, list or tuple.
    full_key:
    object_type=None
```
This makes debugging within large hierarchical structures challenging.

**To Reproduce**
```python
from typing import Tuple
from dataclasses import dataclass
from omegaconf import OmegaConf

@dataclass
class TopLvlConf:
    foo: Tuple[str] = 123

OmegaConf.create(TopLvlConf)
```

**Expected behavior**
The error would specify that the field `foo` is the culprit.

**Additional context**
- [x] OmegaConf version: 2.1.0.dev24
- [x] Python version: 3.8.6
- [x] Operating system: Ubuntu 16.04
- [x] Please provide a minimal repro

### LINKED ISSUE #697: Vague error for equals sign in resolver when creating config from dataclass
**Describe the bug**
If users create their config from dataclass objects (Hydra structured configs) and accidentally put an equals sign in a resolver string, the error traceback is vague and does not point to the offending key

**To Reproduce**

```python
from dataclasses import dataclass
import traceback
from omegaconf import DictConfig, OmegaConf
from omegaconf.errors import GrammarParseError


# The root cause is the equals sign in ``default=``
problematic_equals_resolver = '${oc.env:API_KEY, default=abc123}'

# Dataclass configs (produce vague error)
@dataclass
class ConnectConf:
    api_key: str = problematic_equals_resolver

@dataclass
class TasksConf:
    connect: ConnectConf = ConnectConf()

@dataclass
class Conf:
    tasks: TasksConf = TasksConf()

# Plain dict config (produces good error)
dict_conf = {
    'tasks': {
        'connect': {
            'api_key': problematic_equals_resolver}}}

# Checkout the stack traces
try:
    OmegaConf.create(dict_conf)
except GrammarParseError:
    traceback.print_exc()
    print('^^ Good error showing a ``full_key`` value\n\n')
try:
    OmegaConf.create(Conf)
except GrammarParseError:
    traceback.print_exc()
    print('^^ Vague error with an empty ``full_key``\n\n')
```

**Expected behavior**
Whether the OmegaConf config is created from a plain dict or dataclasses, the error should have `full_key: tasks.connect.api_key`

**Additional context**
- OmegaConf version: 2.1.0.dev24
- Python version: 3.6.13
- Operating system: Ubuntu 18.04

### PR DESCRIPTION
**Pull request by omry**
Closes #697 
Closes #658

This is not really fixing it completely, but the error message is more helpful.
It does indicate the offending type. and the key inside it instead of the full key in the config object. (providing the full key will be handled as a part of #514.

### CODE REVIEW

**Comment by jieru-hu** [comment]
Could you paste what the new error message looks like?

**Comment by omry** [comment]
```python
from dataclasses import dataclass

from omegaconf import OmegaConf


@dataclass
class ConnectConf:
    # The root cause is the equals sign in ``default=``
    api_key: str = "${oc.env:API_KEY, default=abc123}"


@dataclass
class TasksConf:
    connect: ConnectConf = ConnectConf()


OmegaConf.structured(TasksConf)
```

Output:
```
Traceback (most recent call last):
....
omegaconf.errors.GrammarParseError: token recognition error at: '='
    full_key: api_key
    object_type=ConnectConf
```

**Review by jieru-hu — APPROVED** [review]
lgtm

**Comment by Jasha10** [comment]
Looks like a good improvement.
This does close #697, but I think that #658 is not resolved yet:
```python
$ cat tmp658.py
from typing import Tuple
from dataclasses import dataclass
from omegaconf import OmegaConf

@dataclass
class TopLvlConf:
    foo: Tuple[str] = 123

OmegaConf.create(TopLvlConf)
```
```bash
$ python tmp658.py
Traceback (most recent call last):
...
omegaconf.errors.ValidationError: Invalid value assigned: int is not a ListConfig, list or tuple.
    full_key:
    object_type=None
```

**Comment by Jasha10** [comment]
I am working on a diff that will close #658.

**Comment by Jasha10** [comment]
I've pushed a commit to patch #658.
```bash
$ python tmp658.py
Traceback (most recent call last):
...
omegaconf.errors.ValidationError: Invalid value assigned: int is not a ListConfig, list or tuple.
    full_key: foo
    object_type=None
```

**Pull request merged**
