### PR TITLE
Update notebook to synch with the docs

### PR DESCRIPTION
**Pull request by odelalleau**
The main purpose is to get (almost) the same content in the docs and in the notebook.

There is also a minor change to the doc on node interpolation, to make
it clearer that we can use them as config objects (they are not plain
Python dictionaries).

### CODE REVIEW

**Comment by omry** [comment]
it's hard to review in the current form, but I didn't see a change removing the pytest usage.
pytest is not a runtime dependency of OmegaConf so it's not available in the binder by default. we should avoid using it in the example.

**Comment by odelalleau** [comment]
> it's hard to review in the current form, but I didn't see a change removing the pytest usage.

Right, this first PR was just to synch the docs. But I can include the pytest fix in it as well, will be done in a minute.

**Comment by omry** [comment]
no rush.

**Comment by odelalleau** [comment]
Fixed the pytest / binder issue in 37e96d3

**Pull request merged**
