### PR TITLE
isort version 5.0.9

### PR DESCRIPTION
**Pull request by pereman2**
precommit and requirements/dev.txt isort didn't match

### CODE REVIEW

**Comment by omry** [comment]
isort 5 is in very active patching phase right now. is 5.0.1 the latest version?

**Comment by pereman2** [comment]
> isort 5 is in very active patching phase right now. is 5.0.1 the latest version?

In the dev.txt file i saw that the pinned version was 5.0.0 which didn't work so, I pinned 5.0.1 which did work. It's not the last version.

**Comment by omry** [comment]
Switch to the latest?

**Comment by omry** [comment]
dev is pinned to isort~=5.0, which means any 5.0.* version.

**Pull request merged**
