### PR TITLE
spelling fix

### PR DESCRIPTION
**Pull request by anthonytec2**

### CODE REVIEW

**Comment by omry** [comment]
Oh oops. This is one of the most visible errors and no one complained.
good catch.

Can you fix the test as well?

**Comment by omry** [comment]
There is a new unrelated error from a recent mypy upgrade. please rebase and try again.

**Comment by anthonytec2** [comment]
Everything should be good to merge in whenever you are ready.

**Comment by omry** [comment]
Thanks!

**Pull request merged**
