### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by Jasha10**
There is a CI failure in #799.
I want to see if CI fails on the `master` branch.

### CODE REVIEW

**Comment by jieru-hu** [comment]
it's probably still a good idea to upgrade pip. in Hydra's nox, `session.run` is used instead of session install, do you mind giving that a try instead? https://github.com/facebookresearch/hydra/blob/main/noxfile.py#L186-L188

**Comment by layday** [comment]
The issue here is that the `CleanCommand` from `build_helpers` is being called while building omegaconf to install it in the nox session, which wipes the `.nox` folder clean.  You are only experiencing this in 21.3, [because](https://github.com/pypa/pip/blob/main/NEWS.rst):

> - In-tree builds are now the default. ``--use-feature=in-tree-build`` is now
  ignored. ``--use-deprecated=out-of-tree-build`` may be used temporarily to ease
  the transition.

... and is unrelated to the editable issue.

**Comment by layday** [comment]
To clarify, previously, pip would make a copy of your entire project folder in $TMPDIR and build the package there. After 21.3, it runs the build from the project's root.

**Comment by Jasha10** [comment]
Yes indeed, it seems that not only is `pytest-runner` deprecated, but also:
- `setup.py test` is [deprecated](https://github.com/pypa/setuptools/pull/1878)
- The `setuptools.setup` keyword argument `setup_requires` is [deprecated](https://setuptools.pypa.io/en/stable/userguide/dependency_management.html#package-requirement).
- The `setuptools.setup` keyword argument `tests_require` is [deprecated](https://setuptools.pypa.io/en/stable/userguide/dependency_management.html#optional-dependencies).

@omry, do you know if our downstream dependents are relying on omegaconf's `setup.py test` command? If not, we can remove `setup_requires` and `tests_require` from the `setup.py` file so that pip will not need to be pinned for editable installs in the noxfile.

**Comment by Jasha10** [comment]
> I don't know. Maybe the conda package.

Looking at the [recipe](https://github.com/conda-forge/omegaconf-feedstock/blob/1d398211d3bf63699c12712d48e8dfb7beb50e4c/recipe/meta.yaml) in the omegaconf-feedstock repo, I'm confident that `setup.py test` is not being used there.

**Pull request merged**
