### PR TITLE
Tentative support for TypedDict

### LINKED ISSUE #473: Support TypedDict
**Is your feature request related to a problem? Please describe.**

`TypedDict` is a convenient way to tell `mypy` about the allowed keys in a dict. However, using a TypedDict as the type of a structured config causes an error.

```
from omegaconf import OmegaConf, MISSING
import attr
from typing import TypedDict

class Foo(TypedDict):
   foo: str

@attr.s(auto_attribs=True)
class Bar:
   f: Foo = MISSING


Bar(f={'foo': 'a'})
Out [39]:
Bar(f={'foo': 'a'})

In [40]:
OmegaConf.structured(Bar)

Truncated Traceback (Use C-c C-$ to view full TB):
~/dev/devr/py/.venv/lib/python3.8/site-packages/omegaconf/_utils.py in _raise(ex, cause)
    608     else:
    609         ex.__cause__ = None
--> 610     raise ex  # set end OC_CAUSE=1 for full backtrace
    611 
    612 

ValidationError: Unexpected object type : Foo
	full_key: 
	reference_type=None
	object_type=None
```

**Describe the solution you'd like**
I'd like TypedDict to be supported.

### PR DESCRIPTION
**Pull request by omry**
Adds provisional support for typed dict.
Closes #473

### CODE REVIEW

**Comment by pereman2** [comment]
I didn't look at it thoroughly but, can TypedDict be merged successfully ?

**Comment by omry** [comment]
Yes, added a test.
it's treated like a regular dict, there is no additional runtime type safety for it.

**Review by pereman2 — APPROVED** [review]

**Review by odelalleau — COMMENTED** [review]
Sorry, a bit late on that one. I understand that this is only partial support and as a result there is currently no type check on the values, but would have it been easy to at least enforce that the `key_type` of the resulting DictConfig must be a string?

**Comment by omry** [comment]
Seems like a reasonably easy thing to add.

**Pull request merged**
