### PR TITLE
Add manifest file

### LINKED ISSUE #221: Include base/requirements.txt and optionally tests in source dist
Any ETA for releasing the 2.0?

### PR DESCRIPTION
**Pull request by hadim**
Closes #221

### CODE REVIEW

**Comment by hadim** [comment]
@omry Once this is merged and released, I'll update and release the conda package: https://github.com/conda-forge/omegaconf-feedstock/pull/3

**Comment by omry** [comment]
cool.
did you confirm pytest can run on the files in the resulting sdist?

**Comment by omry** [comment]
Confirmed that it does. Thanks!

**Comment by hadim** [comment]
Thanks. Could you make a new rc release?

**Comment by omry** [comment]
should have one soon, still testing it.

**Comment by omry** [comment]
rc26 is out and seems good, I ran into unexpected issues with Hydra but they are not related.

**Pull request merged**
