### PR TITLE
refactor built-in resolvers

### PR DESCRIPTION
**Pull request by omry**
Reorganizing built-in resolvers.

I am also thinking about an alternative layout with a single file per module:
```
oc/__init__.py # oc module
oc/dict.py    # oc.dict module 
```

### CODE REVIEW

**Review by odelalleau — APPROVED** [review]
Sounds good! (not sure we care about defining `__all__` but why not)

**Comment by omry** [comment]
`__all__` there is to allow `from resolvers.oc import env` (if you just import in init and not use it's triggering a lint warning).
the alternative layout should probably eliminate the need for it.

**Review by Jasha10 — APPROVED** [review]
Looks good to me.

**Comment by omry** [comment]
Switched to new layout, I think it's significantly cleaner.

**Pull request merged**
